# Generated by Django 5.1.3 on 2025-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=255)),
                ('email_status', models.CharField(max_length=255)),
                ('preference_flg', models.CharField(max_length=255)),
                ('jwt_token', models.TextField()),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
