# Generated by Django 5.1.3 on 2025-01-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_details_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='access_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='jwt_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mobile_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='preference_flg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
