# Generated by Django 5.1.3 on 2025-01-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_details_access_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
