# Generated by Django 5.1.3 on 2025-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_details_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_key',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('api_keys', models.CharField(max_length=255, null=True)),
                ('api_name', models.CharField(max_length=255, null=True)),
                ('free_count', models.IntegerField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
    ]
