# Generated by Django 5.1.3 on 2025-01-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_preference',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_preference',
            },
        ),
    ]
